---
title: "Project"
output: html_document
---

```{r eval=TRUE, include=FALSE}
library(tidyverse)
#install.packages("gtrendsR")
library(gtrendsR)
#library("docstring")
source("project_utils.R")

```

```{=html}
<style>
    p  {direction: rtl;}
    h1 {text-align: center;}
    h2 {direction: rtl;}
    h4 {direction: rtl;}
    h3 {direction: rtl;text-decoration: underline;}
    ol {direction: rtl;}
    li {direction: rtl;}
</style>
```
<h1><u>מגישים</u></h1>

::: {style="border-bottom:solid"}
:::

```{r}
fmt <- "%Y-%m-%d"

data <- get_data() # the main dataset, contains ads info
rating <- get_rating_data() # contains rating info, e.g., ads cost, viewrs and etc
general <- get_general_data() # ads categories, e.g., beer, car and etc 
```

```{r}
brands = unique(data['brand'])
brand_q <- data %>%
  group_by(brand) %>%
  summarise(count = n())

ggplot(data=brand_q, aes(x=brand, y=count))+
  geom_bar(stat = 'identity')

```

```{r}

brand <-  "Doritos"
dates <-  search_dates(brand)
```

בדיקה על מותג מסוים בכל שנות הסופרבול

```{r}

by_month <- gtopics("Doritos","all") %>%
  group_by(month=month(date)) %>% 
  summarise(hits=mean(hits))

ggplot(by_month, aes(x=month,y=hits)) +
  geom_bar(stat="identity", position=position_dodge())+
 geom_text(aes(label=round(hits)), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)
```

```{r}
by_month <- tibble(hits=as.numeric(NA),type=c(as.character(NA)),brand=c(as.character(NA))) %>%  na.omit()
for (brand in brands$brand) 
{
  all <- gtopics(brand,"all") %>%
  group_by(month=month(date))
  
  ad_years <- sapply(search_dates(brand), year)
  
  t <- tibble(brand=c(brand,brand),
              type=c("NOT Sup month","Sup month"),
              #hits=c(mean(filter(all,month!=2)$hits),mean(filter(all,month==2)$hits)))
              hits=c(mean(filter(all,month!=2 |!(year(date) %in% ad_years))$hits),
                     mean(filter(all,month==2, year(date) %in% ad_years)$hits)))
              
  by_month <- by_month %>% add_row(t)
}

```

להראות פרדוקס סימפסון על E-trade

```{r}
by_month
ggplot(data=by_month, aes(x=brand, y=hits, fill=type, width=0.8)) +
  geom_bar(stat="identity", position=position_dodge())+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()
```

על מנת לעבוד בצורה

```{r}

df <- tibble(date=c(as.character(NA)),
             brand=c(as.character(NA)),
             hits=c(as.numeric(NA)), 
             is_sup_week=c(as.logical(NA)),
             is_sup_year=c(as.logical(NA))) %>% na.omit()


```

```{r}

update_df <- function(df, brand, rday=3)
{ 
  for (y in seq(2004, 2020))
  {
    output <- gtopics(brand, time=sprintf("%s-01-01 %s-12-31",y, y))
    ad_date = search_dates(brand) %>% filter(year(date) == y)
   
    weeks <- rep(FALSE, nrow(output))
    if (nrow(ad_date))
    {
       weeks <- sapply(output$date,
                      function (date) {return((date <= ad_date + rday) & (date >= ad_date - rday))})
    }
  
   
      temp <- tibble(date=output$date,
                     brand=output$keyword, 
                     hits=output$hits,
                     is_sup_week=weeks,
                     is_sup_year=rep(as.logical(nrow(ad_date)),nrow(output))
                    )
   
      df <- df %>% add_row(temp)
    }
   
  return(df)
}
```

```{r}
for (brand in brands$brand) {df <- update_df(df, brand); Sys.sleep(6)}
df$date <- as.Date(df$date)
```

```{r}
head(df)
```

```{r}
by_week <- df %>% 
  group_by(is_sup_week, brand) %>% 
  summarise(hits=mean(hits))
by_week
ggplot(data=by_week, aes(x=brand, y=hits, fill=as.character(is_sup_week), width=0.8)) +
  geom_bar(stat="identity", position=position_dodge())+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()
```

not sure about this one (delete ? )

```{r}
brand="Pepsi"
rday <- 2
i = 10
dates <- search_dates(brand)

by_week <- tibble(year=c(as.numeric(NA)),
             brand=c(as.character(NA)),
             type=c(as.character(NA)),
             hits=c(as.numeric(NA)), 
             is_sup=c(as.numeric(NA))) %>% na.omit()


for (i in seq(nrow(dates)))  
{
  output <- gtopics_r(brand, date=dates[i,], rday)
  sup_weeks <- filter(output, date <= dates[i,] + rday, date >= dates[i,] - rday)
  not_sup_weeks <-  filter(output, !(date %in% sup_weeks$date))
  
  temp <- tibble(year=c(year(dates[i,]),year(dates[i,])),
                 brand=c(brand,brand),
                 type=c("Not Sup week", "Sup week"),
                 hits=c(mean(not_sup_weeks$hits), mean(sup_weeks$hits)),
                 is_sup=c(0,1))
  
  sup_weeks <- sup_weeks %>% add_row(temp)
}
sup_weeks

```

```{r}
by_month <- df %>% 
  group_by(brand, m=(month(date) == 2) & is_sup_year ) %>% 
  summarise(hits=mean(hits))

by_month
ggplot(data=by_month, aes(x=brand, y=hits, fill=m, width=0.8)) +
  geom_bar(stat="identity", position=position_dodge())+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()
```

```{r}
samp_dates=sample(seq(as.Date('2016/04/07'), as.Date('2016/12/28'), by="day"), 30)
brand="Pepsi"
df <- tibble(year=c(as.numeric(NA)), days=c(as.character(NA)), hits=c(as.numeric(NA))) %>% na.omit()

for (i in seq(length(samp_dates)))  
{
  output <- gtopics_r(brand, date=samp_dates[i], rday=2)
  
  temp <- tibble(year=2016,
                                     days='samp',
                                     hits=mean(output$hits))
  df <- df %>% add_row(temp)
}
df

```

```{r}
samp <- sample(df$hits, 220)
samp <- filter(df, is_sup_week==TRUE)$hits
#samp <- (sample(df$hits, 220) -mean(df$hits))/(sd(df$hits)/sqrt(220))
qqnorm(samp)
qqline(samp)
hist(samp, breaks = 11)


qqplot(qunif(ppoints(220)),
       y=df$hits)

qqline(y=df$hits, distribution = function(p) qunif(p))

qqplot(qt(ppoints(100),df=9),
       y=df$hits)

qqline(y=df$hits, distribution = function(p) qt(p,9))

```

```{r}
samp <- sample(filter(df, brand=="Doritos")$hits, 100)
qqnorm(samp)
qqline(samp)

```

```{r}


hits_on_sup <- filter(df, is_sup_week==TRUE)$hits
hits_not_on_sup <- filter(df, is_sup_week==FALSE)$hits


t.test(hits_on_sup, alternative = "greater", mu=79)
t.test(hits_on_sup, sample(hits_not_on_sup, length(hits_on_sup)), alternative = "greater", paired = FALSE, var.equal = 0, mu=25)

#ks.test(df$hits, "punif")
#t.test()
```

testing global normalization algorithm:

```{r}
y = 2017
brand = "NFL"
test <- gtopics(brand, sprintf("%s-01-01 %s-12-31",y, y+1))
#output <- gtopics(brand, time=sprintf("%s-01-01 %s-12-31",2004, 2004))
d1 <- gtopics(brand, sprintf("%s-01-01 %s-12-31",y, y))
m_date <- d1 %>% filter(hits==100) %>% .$date
d2 <- gtopics(brand, sprintf("%s %s-12-31",m_date, y+1))
d1$hits <- d1$hits * (d2[1,]$hits/100)
t <- filter(d1, date < m_date) %>% add_row(d2)


cmp <- t %>% group_by(chits=filter(test,date==date)$hits) %>% summarise(diff=abs(hits- chits))
sprintf("Max diff: %f",max(cmp$diff))
```

```{r}
 b = brands[6,]
ads_cost <- sapply(data$year,
               function (y) { 
                 # avarage price per 1 second (in USD)
                 return(filter(rating,year==y)$cost_of_30_second_ad_usd)
                 }) %>% round()


data <- data %>% mutate(cost=round(duration/30) * ads_cost)
write.csv("data\\superbowl-ads.csv")

#kaki <- data %>% mutate(cost1=duration* round(ads_cost/30), cost2=round(duration/30) * ads_cost)

kaki <- kaki %>% group_by(brand, year) %>% filter(brand==b) %>% select(brand, year, cost1,cost2)


total_cost <- select(kaki,brand, year, cost1,cost2) %>% 
  summarise(cost1=sum(cost1), cost2=sum(cost2)) %>% 
  filter(brand==b)
total_cost
#kaki <- data %>% mutate(cost=t$cost)
#kaki <- kaki %>% mutate(money=duration*cost)
```

```{r}
data[1,]
```

```{r}
sample <- runif(100)

# Perform a one-sample t-test
t_test_result <- t.test(sample, mu = 0.5)

# Print the test result
print(t_test_result)
```

```{r}
#weeks_before_sup <- sapply(filter(df, is_sup_week)$date, function (d) {return(d - 7)})
week_before_sup <- filter(df, is_sup_week)$date - 7
weekk_after_sup <- filter(df, is_sup_week)$date + 7
```

```{r}
data <- data %>% mutate(cost=round(duration/30) * ads_cost)
write.csv(data,"data\\superbowl-ads.csv")
```
